# Generated by Django 6.0.4 on 2026-04-26 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('type', models.CharField(choices=[('hero_carousel', 'Hero Carousel'), ('product_row', 'Product Row'), ('category_banner', 'Category Banner'), ('promo_banner', 'Promo Banner')], max_length=30)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower = higher on page')),
                ('is_active', models.BooleanField(default=True)),
                ('cta_label', models.CharField(blank=True, default='Shop Now', max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=200)),
                ('bg_color', models.CharField(blank=True, max_length=20)),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_sections', to='catalog.category')),
                ('products', models.ManyToManyField(blank=True, related_name='homepage_sections', to='catalog.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
