# Generated by Django 6.0.4 on 2026-06-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_homepagesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='bg_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='homepage/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='products/'),
        ),
    ]
