# Generated by Django 6.0.4 on 2026-04-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. XAF, USD, EUR', max_length=10, unique=True)),
                ('name', models.CharField(help_text='e.g. CFA Franc', max_length=100)),
                ('symbol', models.CharField(help_text='e.g. FCFA, $, €', max_length=10)),
                ('rate', models.DecimalField(decimal_places=6, default=1, help_text='Exchange rate relative to XAF (base). XAF=1, USD≈600, EUR≈655', max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['-is_default', 'code'],
            },
        ),
    ]
